# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rearpb/rearpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rearpb/rearpb.proto',
  package='rearpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13rearpb/rearpb.proto\x12\x06rearpb\"\x14\n\x12HealthCheckRequest\"\x1e\n\x10HealthCheckReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x85\x01\n\x04Rear\x12\x36\n\x08SayHello\x12\x14.rearpb.HelloRequest\x1a\x12.rearpb.HelloReply\"\x00\x12\x45\n\x0bHealthCheck\x12\x1a.rearpb.HealthCheckRequest\x1a\x18.rearpb.HealthCheckReply\"\x00\x62\x06proto3')
)




_HEALTHCHECKREQUEST = _descriptor.Descriptor(
  name='HealthCheckRequest',
  full_name='rearpb.HealthCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=51,
)


_HEALTHCHECKREPLY = _descriptor.Descriptor(
  name='HealthCheckReply',
  full_name='rearpb.HealthCheckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='rearpb.HealthCheckReply.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=83,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='rearpb.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rearpb.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=113,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='rearpb.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rearpb.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['HealthCheckRequest'] = _HEALTHCHECKREQUEST
DESCRIPTOR.message_types_by_name['HealthCheckReply'] = _HEALTHCHECKREPLY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHCHECKREQUEST,
  __module__ = 'rearpb.rearpb_pb2'
  # @@protoc_insertion_point(class_scope:rearpb.HealthCheckRequest)
  ))
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckReply = _reflection.GeneratedProtocolMessageType('HealthCheckReply', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHCHECKREPLY,
  __module__ = 'rearpb.rearpb_pb2'
  # @@protoc_insertion_point(class_scope:rearpb.HealthCheckReply)
  ))
_sym_db.RegisterMessage(HealthCheckReply)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'rearpb.rearpb_pb2'
  # @@protoc_insertion_point(class_scope:rearpb.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'rearpb.rearpb_pb2'
  # @@protoc_insertion_point(class_scope:rearpb.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)



_REAR = _descriptor.ServiceDescriptor(
  name='Rear',
  full_name='rearpb.Rear',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=280,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='rearpb.Rear.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='rearpb.Rear.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_HEALTHCHECKREQUEST,
    output_type=_HEALTHCHECKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REAR)

DESCRIPTOR.services_by_name['Rear'] = _REAR

# @@protoc_insertion_point(module_scope)
