import os

LOG_DIR = os.environ['RBROOT']+"/model_summaries"

PATH_TO_DATASET = '/files/data/users.dat'
DATASET_PATH_PREFIX = '/data/'
BOARD_HOME = '/board/home'



MODEL_STATUS_CREATED =  "CREATED"
MODEL_STATUS_TRAINING = "TRAINING"
MODEL_STATUS_TESTING = "TESTING"
MODEL_STATUS_TRAINED = "TRAINED"
MODEL_STATUS_DEPLOYED = "DEPLOYED"

MODEL_STATUS_ERROR = "ERROR"
MODEL_STATUS_CANCELLED = "CANCELLED"

